version: '2'
services:
  ossec-log-server:
    image: docker.io/kalaksi/ossec-log-server
    # You can also use GitLab as an alternative to Docker Hub:
    # image: registry.gitlab.com/kalaksi-containers/ossec-log-server
    restart: unless-stopped
    volumes:
      - ossec-log-server:/var/ossec/data
    # TODO: test what other CAPs are needed
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - NET_BIND_SERVICE
    ports:
      - 514:514/tcp
    environment:
      # Exclude from Logspout in case it is used to deliver logs to this container.
      LOGSPOUT: ignore
      OSSEC_EMAIL_NOTIFICATION: "no"
      OSSEC_EMAIL_TO: root@yourdomain
      OSSEC_EMAIL_FROM: ossecm@yourdomain
      OSSEC_SMTP_SERVER: mailserver.yourdomain
      # Comma-separated list of allowed IPs / networks
      OSSEC_ALLOWED_IPS: 10.0.0.0/8,172.17.0.0/16
      OSSEC_SYSLOG_PROTOCOL: tcp

volumes:
  ossec-log-server: {}
